apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerapp-liveness-readiness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockerapp
  template:
    metadata:
      labels:
        app: dockerapp
    spec:
      containers:
        - name: docker-app
          image: arpitb/docker-app
          ports:
            - name: nodejs-port
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: nodejs-port
            initialDelaySeconds: 15
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: nodejs-port
            initialDelaySeconds: 15
            timeoutSeconds: 30