apiVersion: v1
kind: ReplicationController
metadata:
  name: dockerapp-controller
spec:
  replicas: 2
  selector:
    app: dockerapp
  template:
    metadata:
      labels:
        app: dockerapp
    spec:
      containers:
        - name: docker-app
          image: arpitb/docker-app
          ports:
            - name: nodejs-port
              containerPort: 3000