apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworlddb-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworlddb
  template:
    metadata:
      labels:
        app: helloworlddb
    spec:
      containers:
        - name: docker-app
          image: arpitb/docker-app
          command: ["node", "index-db.js"]
          ports:
            - name: nodejs-port
              containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: database-service
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: rootPassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database