apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-rc
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: docker-app
          image: arpitb/docker-app
          ports:
            - name: nodejs-port
              containerPort: 3000