apiVersion: v1
kind: Pod
metadata:
  name: helloworld-pod
  labels:
    app: helloworld
spec:
  containers:
    - name: docker-app
      image: arpitb/docker-app
      ports:
        - name: nodejs-port
          containerPort: 3000